server:
  port: 8082

spring:
  application:
    name: Favourite-Service
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.olvxp.mongodb.net/test
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/